/* ============================================================
   InstaSpace — Email Database (Beta Testing)
      Collects emails from sign-up and beta interest forms.
         Persists to localStorage; readable from the Admin console.
            ============================================================ */
            (function () {
              'use strict';

                var LS_KEY = 'instaspace-emails-v1';

                  /* Load persisted list or start fresh */
                    function _load() {
                        try {
                              var raw = localStorage.getItem(LS_KEY);
                                    if (raw) return JSON.parse(raw);
                                        } catch (e) {}
                                            return [];
                                              }

                                                function _save(list) {
                                                    try { localStorage.setItem(LS_KEY, JSON.stringify(list)); } catch (e) {}
                                                      }

                                                        var EmailDB = {
                                                            /**
                                                                 * Add an email to the database.
                                                                      * @param {string} email  - The email address to store.
                                                                           * @param {string} source - Where it came from, e.g. 'signup', 'beta-form'.
                                                                                * @param {string} role   - User role at sign-up ('host', 'guest', etc.).
                                                                                     * @returns {boolean} true if inserted, false if already present.
                                                                                          */
                                                                                              add: function (email, source, role) {
                                                                                                    if (!email || typeof email !== 'string') return false;
                                                                                                          var clean = email.trim().toLowerCase();
                                                                                                                if (!clean || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(clean)) return false;
                                                                                                                
                                                                                                                      var list = _load();
                                                                                                                            /* deduplicate */
                                                                                                                                  for (var i = 0; i < list.length; i++) {
                                                                                                                                          if (list[i].email === clean) return false;
                                                                                                                                                }
                                                                                                                                                      list.push({
                                                                                                                                                              id:        'em' + Date.now(),
                                                                                                                                                                      email:     clean,
                                                                                                                                                                              source:    source || 'unknown',
                                                                                                                                                                                      role:      role   || 'unknown',
                                                                                                                                                                                              timestamp: new Date().toISOString()
                                                                                                                                                                                                    });
                                                                                                                                                                                                          _save(list);
                                                                                                                                                                                                                return true;
                                                                                                                                                                                                                    },
                                                                                                                                                                                                                    
                                                                                                                                                                                                                        /** Return a shallow copy of all collected email records. */
                                                                                                                                                                                                                            list: function () {
                                                                                                                                                                                                                                  return _load().slice();
                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                          /** Total count of collected emails. */
                                                                                                                                                                                                                                              count: function () {
                                                                                                                                                                                                                                                    return _load().length;
                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                            /**
                                                                                                                                                                                                                                                                 * Export all emails as a CSV string.
                                                                                                                                                                                                                                                                      * Columns: id, email, source, role, timestamp
                                                                                                                                                                                                                                                                           */
                                                                                                                                                                                                                                                                               toCSV: function () {
                                                                                                                                                                                                                                                                                     var rows = _load();
                                                                                                                                                                                                                                                                                           var header = 'id,email,source,role,timestamp';
                                                                                                                                                                                                                                                                                                 var lines = rows.map(function (r) {
                                                                                                                                                                                                                                                                                                         return [r.id, r.email, r.source, r.role, r.timestamp].join(',');
                                                                                                                                                                                                                                                                                                               });
                                                                                                                                                                                                                                                                                                                     return [header].concat(lines).join('\n');
                                                                                                                                                                                                                                                                                                                         },
                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                             /**
                                                                                                                                                                                                                                                                                                                                  * Trigger a browser download of the CSV file.
                                                                                                                                                                                                                                                                                                                                       */
                                                                                                                                                                                                                                                                                                                                           downloadCSV: function () {
                                                                                                                                                                                                                                                                                                                                                 var csv  = this.toCSV();
                                                                                                                                                                                                                                                                                                                                                       var blob = new Blob([csv], { type: 'text/csv' });
                                                                                                                                                                                                                                                                                                                                                             var url  = URL.createObjectURL(blob);
                                                                                                                                                                                                                                                                                                                                                                   var a    = document.createElement('a');
                                                                                                                                                                                                                                                                                                                                                                         a.href     = url;
                                                                                                                                                                                                                                                                                                                                                                               a.download = 'instaspace-beta-emails.csv';
                                                                                                                                                                                                                                                                                                                                                                                     document.body.appendChild(a);
                                                                                                                                                                                                                                                                                                                                                                                           a.click();
                                                                                                                                                                                                                                                                                                                                                                                                 document.body.removeChild(a);
                                                                                                                                                                                                                                                                                                                                                                                                       URL.revokeObjectURL(url);
                                                                                                                                                                                                                                                                                                                                                                                                           },
                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                               /** Clear all stored emails (admin use only). */
                                                                                                                                                                                                                                                                                                                                                                                                                   clear: function () {
                                                                                                                                                                                                                                                                                                                                                                                                                         _save([]);
                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                               };
                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                 window.EmailDB = EmailDB;
                                                                                                                                                                                                                                                                                                                                                                                                                                 })();
